### ISSUE TITLE
How to install third-party package in Jupyter of TVB?

### ISSUE THREAD

**Issue by freedom1979** [the-virtual-brain/tvb-root#576]
#### Describe the new feature or enhancement
*Please provide a clear and concise description of what you want to add or
change.*

#### Describe your proposed implementation
*Describe how you think the feature or improvement should be implemented (e.g., 
as a new method on an existing class? as new capability added to an existing
method?) If you're not sure, please delete this section and the next section.*

#### Describe possible alternatives
*If you've suggested an implementation above, list here any alternative
implementations you can think of, and brief comments explaining why the chosen
implementation is better.*

#### Additional comments
*Add any other context or screenshots about the feature request here.*

**Comment by freedom1979** [comment]
How to install third-party package for TVB?

**Comment by maedoc** [comment]
Hi, thanks for your interest.  The issue tracker is not for answering support questions: please see the mailing list over here: https://groups.google.com/g/tvb-users

That said, you should be able to use the cell magic
```
%pip install autograd
```
to install the autograd package int he environment in which TVB's jupyter is running.
