### ISSUE TITLE
Wilson Cowan Sigmoid Function signed changed

### ISSUE THREAD

**Issue by julioRodino** [the-virtual-brain/tvb-root#667]
In the wilson_cowan.py script the sigmoid function is defined as follows in the comments (and in the papers):
            \tau \dot{x}(t) &= -z(t) + \phi(z(t)) \\
            \phi(x) &= \frac{c}{1-exp(-a (x-b))}

But the code deffines the sigmoid function:
```
if self.shift_sigmoid:
            s_e = self.c_e * (1.0 / (1.0 + numpy.exp(-self.a_e * (x_e - self.b_e))) - 1.0
                              / (1.0 + numpy.exp(-self.a_e * -self.b_e)))
            s_i = self.c_i * (1.0 / (1.0 + numpy.exp(-self.a_i * (x_i - self.b_i))) - 1.0
                              / (1.0 + numpy.exp(-self.a_i * -self.b_i)))
        else:
            s_e = self.c_e / (1.0 + numpy.exp(-self.a_e * (x_e - self.b_e)))
            s_i = self.c_i / (1.0 + numpy.exp(-self.a_i * (x_i - self.b_i)))
```
Following the formula, it should be:

```
if self.shift_sigmoid:
            s_e = self.c_e * (1.0 / (1.0 - numpy.exp(-self.a_e * (x_e - self.b_e))) - 1.0
                              / (1.0 - numpy.exp(-self.a_e * -self.b_e)))
            s_i = self.c_i * (1.0 / (1.0 - numpy.exp(-self.a_i * (x_i - self.b_i))) - 1.0
                              / (1.0 - numpy.exp(-self.a_i * -self.b_i)))
        else:
            s_e = self.c_e / (1.0 - numpy.exp(-self.a_e * (x_e - self.b_e)))
            s_i = self.c_i / (1.0 - numpy.exp(-self.a_i * (x_i - self.b_i)))
```
Changing from adding the exponential to  subtracting it.

**Comment by maedoc** [comment]
[Wilson & Cowan 1972](https://pubmed.ncbi.nlm.nih.gov/4332108/) define their sigmoid function as 

<img width="504" alt="image" src="https://user-images.githubusercontent.com/5189886/231972510-300bb1ed-18a1-4e24-93b1-fa30878e30cf.png">

so the docstring might be wrong, unfortunately.  the main point is that it's a sigmoid function which is a family of functions which saturate.  This is not the case for $1/1-e^{-x}$:

```python
x = np.r_[-10:10:128j]
f1 = 1/(1+np.exp(-x))
f2 = 1/(1-np.exp(-x))
plot(x, f1)
plot(x, f2)
ylim([-0.2,1.2])
legend(('1/(1+np.exp(-x))', '1/(1-np.exp(-x))'))
grid(1)
```
![image](https://user-images.githubusercontent.com/5189886/231973346-3f73ec9a-6666-42d7-a9ff-0bb1bfa35199.png)
